# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q9jHDNiESre-bsu83GqO9IzUCqJ55EcU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("mnist_train.csv")

print(df.head(5))
 l = df['label']
d = df.drop('label',axis = 1)

print(d.shape)
print(l.shape)

plt.figure(figsize=(7,7))
idx = 150
grid_data = d.iloc[idx].values.reshape(28,28)
plt.imshow(grid_data, interpolation='none', cmap='gray')
plt.show()
print(l[idx])